### ISSUE TITLE
Undefined values casue exit in say on line 282

### ISSUE THREAD

**Issue by blademaster2005** [celogeek/MoviesOrganizer#1]
IMDB Search > CSI: Crime Scene Investigation  
Movie/Series Year > 2000  
Movie    : CSI: Crime Scene Investigation
Kind     : Tv Serie
Year     : 2000
Use of uninitialized value in say at /usr/local/share/perl/5.10.1/Movies/Organizer.pm line 282.

If you wrap your say statements in if defined such as 

if (defined $imdb->{plot} ) {say "Plot     : ", $imdb->{plot};}

This avoids the catastrophic crash. 

Now this may be a deeper issue of not parsing the plot properly.

**Comment by celogeek** [comment]
fixed in 1.2
